#!/usr/bin/env bash

set -e

cd ~/.password-store
fl="$(find . -name '*.gpg' -print | rofi -dmenu -p "pass")"
nm="${fl%.*}"

sel="$(printf "pw\notp\n" | rofi -dmenu -p "type")"
case $sel in
    pw)
        pass -c ${nm}
    ;;
    otp)
        pass otp -c ${nm}
    ;;
    *)
    exit 1
    ;;
esac
