#!/usr/bin/env bash

set -e

sel="$(printf "shutdown\nreboot\nlockscreen\n" | rofi -dmenu -p 'action')"
case $sel in
    shutdown)
        shutdown 0
    ;;
    reboot)
        reboot
    ;;
    lockscreen)
        swaylock -f -c 202020
    ;;
    *)
    exit 1
    ;;
esac
